version: '2'
catalog:
  name: third-data-api
  version: 1.0.0
services:
  zipkin:
    retain_ip: true
    scale: 1
    start_on_create: true
  service-config:
    scale: 2
    start_on_create: true
  lb:
    scale: 1
    start_on_create: true
  edge-server:
    scale: 2
    start_on_create: true
  service-monitor:
    scale: 1
    start_on_create: true
  discovery2:
    retain_ip: true
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      recreate_on_quorum_strategy_config:
        quorum: 1
      port: 8761
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreateOnQuorum
      request_line: GET "/" "HTTP/1.0"
      reinitializing_timeout: 60000
  discovery1:
    retain_ip: true
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 2000
      port: 8761
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 3000
      strategy: recreate
      request_line: GET "/" "HTTP/1.0"
      reinitializing_timeout: 60000
  daas-monitor:
    retain_ip: true
    scale: 1
    start_on_create: true
