version: '2'
services:
  rongshu:
    image: 10.1.241.80:5000/third-rongshu
    environment:
      eureka.client.service-url.defaultZone: http://10.42.1.33:8761/eureka/
      zipkin.server-url: http://10.42.246.135:9411
      eureka.instance.preferIpAddress: 'true'
      eureka.instance.instance-id: $${spring.cloud.client.ipAddress}:$${server.port}
    stdin_open: true
    tty: true
    ports:
    - 12122:12122/tcp
    labels:
      io.rancher.container.pull_image: always